"""Display labels, module routing, and description formats for the system activity log."""

from app.config.enums import LogAction, LogModule


LOG_MODULE_LABELS: dict[LogModule, str] = {
    LogModule.AUTH: "Authentication",
    LogModule.OPPORTUNITY: "Opportunity",
    LogModule.PIPELINE: "Pipeline",
    LogModule.PROFILE_VARIANT: "Profile Variant",
    LogModule.PROJECT: "Project",
    LogModule.SALES_ENABLEMENT: "Sales Enablement",
    LogModule.USER_MANAGEMENT: "User Management",
    LogModule.SETTINGS: "Settings",
    LogModule.EXPORT: "Export",
}

LOG_ACTION_LABELS: dict[LogAction, str] = {
    LogAction.USER_LOGIN: "User Login",
    LogAction.USER_LOGOUT: "User Logout",
    LogAction.USER_SIGNUP: "User Signup",
    LogAction.PASSWORD_RESET: "Password Reset",
    LogAction.OPPORTUNITY_CREATED: "Opportunity Created",
    LogAction.OPPORTUNITY_UPDATED: "Opportunity Updated",
    LogAction.OPPORTUNITY_STATUS_CHANGED: "Opportunity Status Changed",
    LogAction.OPPORTUNITY_DELETED: "Opportunity Deleted",
    LogAction.OPPORTUNITY_AI_INGESTED: "Opportunity Ingested by AI",
    LogAction.COMMENT_ADDED: "Comment Added",
    LogAction.COMMENT_REPLIED: "Comment Replied",
    LogAction.COMMENT_UPDATED: "Comment Updated",
    LogAction.COMMENT_DELETED: "Comment Deleted",
    LogAction.PIPELINE_PROJECT_CREATED: "Pipeline Project Created",
    LogAction.PIPELINE_PROJECT_UPDATED: "Pipeline Project Updated",
    LogAction.PIPELINE_PROJECT_DELETED: "Pipeline Project Deleted",
    LogAction.PIPELINE_RESOURCE_CREATED: "Pipeline Resource Created",
    LogAction.PIPELINE_RESOURCE_UPDATED: "Pipeline Resource Updated",
    LogAction.PIPELINE_RESOURCE_DELETED: "Pipeline Resource Deleted",
    LogAction.PIPELINE_RESOURCE_SELECTED: "Pipeline Resource Selected",
    LogAction.PIPELINE_RESOURCE_ASSIGNED_TO_TL: "Pipeline Resource Assigned to Team Lead",
    LogAction.PIPELINE_RESOURCE_APPROVED: "Pipeline Resource Approved",
    LogAction.PIPELINE_RESOURCE_AUTO_APPROVED: "Pipeline Resource Auto Approved",
    LogAction.PIPELINE_RESOURCE_REJECTED: "Pipeline Resource Rejected",
    LogAction.PIPELINE_TECH_PREP_CREATED: "Technical Preparation Created",
    LogAction.PIPELINE_TECH_PREP_UPDATED: "Technical Preparation Updated",
    LogAction.PIPELINE_TECH_PREP_DELETED: "Technical Preparation Deleted",
    LogAction.PIPELINE_TECH_PREP_COMMENTED: "Technical Preparation Commented",
    LogAction.PROFILE_VARIANT_CREATED: "Profile Variant Created",
    LogAction.PROFILE_VARIANT_UPDATED: "Profile Variant Updated",
    LogAction.PROFILE_VARIANT_DELETED: "Profile Variant Deleted",
    LogAction.PROFILE_DOWNLOADED: "Profile Downloaded",
    LogAction.PROJECT_CREATED: "Project Created",
    LogAction.PROJECT_UPDATED: "Project Updated",
    LogAction.PROJECT_DELETED: "Project Deleted",
    LogAction.CASE_STUDY_DOWNLOADED: "Case Study Downloaded",
    LogAction.SALES_ENABLEMENT_CREATED: "Sales Enablement Created",
    LogAction.SALES_ENABLEMENT_UPDATED: "Sales Enablement Updated",
    LogAction.SALES_ENABLEMENT_DELETED: "Sales Enablement Deleted",
    LogAction.USER_INVITED: "User Invited",
    LogAction.USER_ROLE_CHANGED: "User Role Changed",
    LogAction.USER_STATUS_CHANGED: "User Status Changed",
    LogAction.USER_DELETED: "User Deleted",
    LogAction.USER_BENCHED: "User Moved to Bench",
    LogAction.USER_HIERARCHY_REPAIRED: "Reporting Hierarchy Repaired",
    LogAction.ROLE_PERMISSION_CREATED: "Role Permission Created",
    LogAction.ROLE_PERMISSION_UPDATED: "Role Permission Updated",
    LogAction.ROLE_PERMISSION_DELETED: "Role Permission Deleted",
    LogAction.CSV_EXPORTED: "CSV Exported",
}

# Which module each action belongs to, so `log_activity` derives it instead of every call
# site passing a module that could drift out of step with the action.
LOG_ACTION_MODULES: dict[LogAction, LogModule] = {
    LogAction.USER_LOGIN: LogModule.AUTH,
    LogAction.USER_LOGOUT: LogModule.AUTH,
    LogAction.USER_SIGNUP: LogModule.AUTH,
    LogAction.PASSWORD_RESET: LogModule.AUTH,
    LogAction.OPPORTUNITY_CREATED: LogModule.OPPORTUNITY,
    LogAction.OPPORTUNITY_UPDATED: LogModule.OPPORTUNITY,
    LogAction.OPPORTUNITY_STATUS_CHANGED: LogModule.OPPORTUNITY,
    LogAction.OPPORTUNITY_DELETED: LogModule.OPPORTUNITY,
    LogAction.OPPORTUNITY_AI_INGESTED: LogModule.OPPORTUNITY,
    LogAction.COMMENT_ADDED: LogModule.OPPORTUNITY,
    LogAction.COMMENT_REPLIED: LogModule.OPPORTUNITY,
    LogAction.COMMENT_UPDATED: LogModule.OPPORTUNITY,
    LogAction.COMMENT_DELETED: LogModule.OPPORTUNITY,
    LogAction.PIPELINE_PROJECT_CREATED: LogModule.PIPELINE,
    LogAction.PIPELINE_PROJECT_UPDATED: LogModule.PIPELINE,
    LogAction.PIPELINE_PROJECT_DELETED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_CREATED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_UPDATED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_DELETED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_SELECTED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_ASSIGNED_TO_TL: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_APPROVED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_AUTO_APPROVED: LogModule.PIPELINE,
    LogAction.PIPELINE_RESOURCE_REJECTED: LogModule.PIPELINE,
    LogAction.PIPELINE_TECH_PREP_CREATED: LogModule.PIPELINE,
    LogAction.PIPELINE_TECH_PREP_UPDATED: LogModule.PIPELINE,
    LogAction.PIPELINE_TECH_PREP_DELETED: LogModule.PIPELINE,
    LogAction.PIPELINE_TECH_PREP_COMMENTED: LogModule.PIPELINE,
    LogAction.PROFILE_VARIANT_CREATED: LogModule.PROFILE_VARIANT,
    LogAction.PROFILE_VARIANT_UPDATED: LogModule.PROFILE_VARIANT,
    LogAction.PROFILE_VARIANT_DELETED: LogModule.PROFILE_VARIANT,
    LogAction.PROFILE_DOWNLOADED: LogModule.PROFILE_VARIANT,
    LogAction.PROJECT_CREATED: LogModule.PROJECT,
    LogAction.PROJECT_UPDATED: LogModule.PROJECT,
    LogAction.PROJECT_DELETED: LogModule.PROJECT,
    LogAction.CASE_STUDY_DOWNLOADED: LogModule.PROJECT,
    LogAction.SALES_ENABLEMENT_CREATED: LogModule.SALES_ENABLEMENT,
    LogAction.SALES_ENABLEMENT_UPDATED: LogModule.SALES_ENABLEMENT,
    LogAction.SALES_ENABLEMENT_DELETED: LogModule.SALES_ENABLEMENT,
    LogAction.USER_INVITED: LogModule.USER_MANAGEMENT,
    LogAction.USER_ROLE_CHANGED: LogModule.USER_MANAGEMENT,
    LogAction.USER_STATUS_CHANGED: LogModule.USER_MANAGEMENT,
    LogAction.USER_DELETED: LogModule.USER_MANAGEMENT,
    LogAction.USER_BENCHED: LogModule.USER_MANAGEMENT,
    LogAction.USER_HIERARCHY_REPAIRED: LogModule.USER_MANAGEMENT,
    LogAction.ROLE_PERMISSION_CREATED: LogModule.SETTINGS,
    LogAction.ROLE_PERMISSION_UPDATED: LogModule.SETTINGS,
    LogAction.ROLE_PERMISSION_DELETED: LogModule.SETTINGS,
    LogAction.CSV_EXPORTED: LogModule.EXPORT,
}

# The system-log list reads "{user} {verb}", composed at write time so the sentence still
# reads correctly after the entity it names is renamed or deleted.
SYSTEM_LOG_DESCRIPTION = "{user} {verb}"

SYSTEM_LOG_DESCRIPTION_WITH_ENTITY = '{user} {verb} "{entity}"'

SYSTEM_LOG_MAX_DESCRIPTION_LENGTH = 500

# Past-tense phrase used to build a description when a call site does not supply one.
LOG_ACTION_VERBS: dict[LogAction, str] = {
    LogAction.USER_LOGIN: "logged in",
    LogAction.USER_LOGOUT: "logged out",
    LogAction.USER_SIGNUP: "signed up",
    LogAction.PASSWORD_RESET: "reset their password",
    LogAction.OPPORTUNITY_CREATED: "created opportunity",
    LogAction.OPPORTUNITY_UPDATED: "updated opportunity",
    LogAction.OPPORTUNITY_STATUS_CHANGED: "changed the status of opportunity",
    LogAction.OPPORTUNITY_DELETED: "deleted opportunity",
    LogAction.OPPORTUNITY_AI_INGESTED: "ingested opportunity via AI",
    # Every one of these reads as `{user} {verb} "{entity}"`, with the entity being the
    # opportunity the comment hangs off - the page itself belongs in `details`.
    LogAction.COMMENT_ADDED: "commented on",
    LogAction.COMMENT_REPLIED: "replied to a comment on",
    LogAction.COMMENT_UPDATED: "edited their comment on",
    LogAction.COMMENT_DELETED: "deleted their comment on",
    LogAction.PIPELINE_PROJECT_CREATED: "created pipeline project",
    LogAction.PIPELINE_PROJECT_UPDATED: "updated pipeline project",
    LogAction.PIPELINE_PROJECT_DELETED: "deleted pipeline project",
    LogAction.PIPELINE_RESOURCE_CREATED: "added pipeline resource",
    LogAction.PIPELINE_RESOURCE_UPDATED: "updated pipeline resource",
    LogAction.PIPELINE_RESOURCE_DELETED: "removed pipeline resource",
    LogAction.PIPELINE_RESOURCE_SELECTED: "selected pipeline resource",
    LogAction.PIPELINE_RESOURCE_ASSIGNED_TO_TL: "assigned to a team lead pipeline resource",
    LogAction.PIPELINE_RESOURCE_APPROVED: "approved pipeline resource",
    LogAction.PIPELINE_RESOURCE_AUTO_APPROVED: "auto approved pipeline resource",
    LogAction.PIPELINE_RESOURCE_REJECTED: "rejected pipeline resource",
    LogAction.PIPELINE_TECH_PREP_CREATED: "created technical preparation",
    LogAction.PIPELINE_TECH_PREP_UPDATED: "updated technical preparation",
    LogAction.PIPELINE_TECH_PREP_DELETED: "deleted technical preparation",
    LogAction.PIPELINE_TECH_PREP_COMMENTED: "commented on technical preparation",
    LogAction.PROFILE_VARIANT_CREATED: "created profile variant",
    LogAction.PROFILE_VARIANT_UPDATED: "updated profile variant",
    LogAction.PROFILE_VARIANT_DELETED: "deleted profile variant",
    LogAction.PROFILE_DOWNLOADED: "downloaded profile",
    LogAction.PROJECT_CREATED: "created project",
    LogAction.PROJECT_UPDATED: "updated project",
    LogAction.PROJECT_DELETED: "deleted project",
    LogAction.CASE_STUDY_DOWNLOADED: "downloaded case study",
    LogAction.SALES_ENABLEMENT_CREATED: "created sales enablement entry",
    LogAction.SALES_ENABLEMENT_UPDATED: "updated sales enablement entry",
    LogAction.SALES_ENABLEMENT_DELETED: "deleted sales enablement entry",
    LogAction.USER_INVITED: "invited user",
    LogAction.USER_ROLE_CHANGED: "changed the role of user",
    LogAction.USER_STATUS_CHANGED: "changed the status of user",
    LogAction.USER_DELETED: "deleted user",
    # Ends on the entity noun like its neighbours, so SYSTEM_LOG_DESCRIPTION_WITH_ENTITY
    # reads '{actor} moved to bench user "{name}"'.
    LogAction.USER_BENCHED: "moved to bench user",
    # A sweep over many users, so it names no entity - the handler passes an explicit
    # description carrying the counts, and this verb is only the fallback sentence.
    LogAction.USER_HIERARCHY_REPAIRED: "repaired the reporting hierarchy",
    LogAction.ROLE_PERMISSION_CREATED: "created role permissions for",
    LogAction.ROLE_PERMISSION_UPDATED: "updated role permissions for",
    LogAction.ROLE_PERMISSION_DELETED: "deleted role permissions for",
    LogAction.CSV_EXPORTED: "exported CSV",
}
