from enum import Enum

class NotificationType(str,Enum):
    PIPELINE_ANALYSIS = "PIPELINE_ANALYSIS"
    RELAVENT_PROJECTS = "RELAVENT_PROJECTS"
    SALES_ENABLEMENT = "SALES_ENABLEMENT"
    DISCOVERY_QUESTIONS = "DISCOVERY_QUESTIONS"
    OUTREACH_TEMPLATE = "OUTREACH_TEMPLATE"
    SALES_TALKING_POINTS = "SALES_TALKING_POINTS"
    SETTINGS = "SETTINGS"
    INFO = "INFO"
    