"""Add company_profile to Opportunity as JSONB

Revision ID: 017f0df5a222
Revises: d230537fb7b8
Create Date: 2026-07-31 18:01:57.466591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017f0df5a222'
down_revision: Union[str, None] = 'd230537fb7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('opportunities', sa.Column('level', sa.String(length=100), nullable=True))
    op.add_column('opportunities', sa.Column('posted_date', sa.String(length=100), nullable=True))
    op.add_column('opportunities', sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('opportunities', sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('opportunities', sa.Column('client_information', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('company_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('opportunities', 'contact')
    op.drop_column('opportunities', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('opportunities', 'company_profile')
    op.drop_column('opportunities', 'client_information')
    op.drop_column('opportunities', 'preferred_skills')
    op.drop_column('opportunities', 'required_skills')
    op.drop_column('opportunities', 'posted_date')
    op.drop_column('opportunities', 'level')
    op.drop_column('opportunities', 'duration')
    op.drop_column('opportunities', 'role')
    op.drop_column('opportunities', 'industry')
    # ### end Alembic commands ###
