"""Removed Relavent projects column in sales enablement

Revision ID: 020a7a4f4ba6
Revises: 882a6b6a4936
Create Date: 2026-08-10 18:28:41.811081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020a7a4f4ba6'
down_revision: Union[str, None] = '882a6b6a4936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_enablement', 'relevant_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_enablement', sa.Column('relevant_projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
