"""Move fullName to first_name and last_name

Revision ID: 035c69a2da25
Revises: d76248adc166
Create Date: 2026-08-06 13:05:01.201835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035c69a2da25'
down_revision: Union[str, None] = 'd76248adc166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_info', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('user_personal_info', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.alter_column('user_personal_info', 'primary_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_personal_info', 'working_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'fullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('user_personal_info', 'working_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_personal_info', 'primary_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_personal_info', 'last_name')
    op.drop_column('user_personal_info', 'first_name')
    # ### end Alembic commands ###
