"""make opportunity updatedAt non-nullable

Revision ID: 0a145d99489a
Revises: 020a7a4f4ba6
Create Date: 2026-08-10 22:04:27.422306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a145d99489a'
down_revision: Union[str, None] = '020a7a4f4ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE opportunities SET "updatedAt" = now() WHERE "updatedAt" IS NULL')
    op.alter_column('opportunities', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
