"""User Invitation table created 

Revision ID: 0ba0e10ed2af
Revises: 8900cc375320
Create Date: 2026-08-06 14:22:02.001784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba0e10ed2af'
down_revision: Union[str, None] = '8900cc375320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_email', sa.String(length=100), nullable=False),
    sa.Column('roleID', sa.Integer(), nullable=False),
    sa.Column('reporting_to', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'CANCELLED', name='invitationstatus'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('invitedBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invitedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporting_to'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roleID'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
