"""Added reportingto id 

Revision ID: 0f4d60742350
Revises: e0252bc96563
Create Date: 2026-07-31 09:33:35.666758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4d60742350'
down_revision: Union[str, None] = 'e0252bc96563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reporting_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['reporting_to'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'reporting_to')
    # ### end Alembic commands ###
