"""Drop work_email from user_personal_info

Revision ID: 1ceadda60289
Revises: 0ba0e10ed2af
Create Date: 2026-08-06 14:30:03.027307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ceadda60289'
down_revision: Union[str, None] = '0ba0e10ed2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_personal_info', 'work_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_info', sa.Column('work_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
