"""Removed relavent projects from sales enablement

Revision ID: 1d49bb99a4d0
Revises: 7cf2062fe8e1
Create Date: 2026-08-10 17:30:56.114882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d49bb99a4d0'
down_revision: Union[str, None] = '7cf2062fe8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_enablement', 'relevant_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_enablement', sa.Column('relevant_projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
