"""Removed Project-Domain Dependency

Revision ID: 1ed4e2f0b0e9
Revises: 523dc35bea42
Create Date: 2026-08-05 16:23:17.876439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed4e2f0b0e9'
down_revision: Union[str, None] = '523dc35bea42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_domains')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_domains',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('createdBy', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updatedBy', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], name='project_domains_createdBy_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], name='project_domains_updatedBy_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('domain', name='project_domains_domain_key')
    )
    # ### end Alembic commands ###
