"""remove unique constraint from project_name in profile_variant_projects

Revision ID: 2b4adec72046
Revises: aca7e33fc7df
Create Date: 2026-08-11 17:10:23.725034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4adec72046'
down_revision: Union[str, None] = 'aca7e33fc7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_variant_projects_project_name_key', 'profile_variant_projects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_variant_projects_project_name_key', 'profile_variant_projects', ['project_name'])
    # ### end Alembic commands ###
