"""Initial Commit 

Revision ID: 2c0fe57ddbb7
Revises: 
Create Date: 2026-08-08 23:20:58.863966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c0fe57ddbb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('feature_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_feature_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_feature_id'], ['features.feature_id'], ),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_table('menus',
    sa.Column('menu_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_table('opportunity_status',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('permission_key', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_key')
    )
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_account_linked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('account_url', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('roleName', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('menu_roles',
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assignedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_id', 'role_id')
    )
    op.create_table('rolePermissions',
    sa.Column('role_permission_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.feature_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashedPassword', sa.String(length=150), nullable=True),
    sa.Column('refUID', sa.String(length=50), nullable=True),
    sa.Column('passwordResetAt', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('reporting_to', sa.UUID(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporting_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('branches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('roleName', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roleName')
    )
    op.create_table('opportunities',
    sa.Column('opportunityID', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('posted_date', sa.String(length=100), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('benefits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('client_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('ai_job_summary', sa.Text(), nullable=True),
    sa.Column('required_proposal_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('company_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_posting_url', sa.String(length=255), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('is_ai_scraped', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('additional_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['opportunity_status.id'], ),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunityID')
    )
    op.create_table('project_domains',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('isRevoked', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('tech_stacks',
    sa.Column('techstack_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('techstack_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('techstack_id'),
    sa.UniqueConstraint('techstack_name')
    )
    op.create_table('user_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_email', sa.String(length=100), nullable=False),
    sa.Column('roleID', sa.UUID(), nullable=False),
    sa.Column('reporting_to', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'CANCELLED', name='invitationstatus'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('invitedBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invitedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporting_to'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roleID'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_status',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('displayName', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('displayName')
    )
    op.create_table('profile_variants',
    sa.Column('profile_variant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.UUID(), nullable=False),
    sa.Column('experience', sa.String(length=255), nullable=False),
    sa.Column('highlighted_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('upload_profile', sa.String(length=255), nullable=False),
    sa.Column('certificate', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_draft', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_variant_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('case_study', sa.String(length=255), nullable=True),
    sa.Column('projectDomainID', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectDomainID'], ['project_domains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('sales_enablement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunityID', sa.UUID(), nullable=False),
    sa.Column('suggested_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sales_talking_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('outreach_template', sa.Text(), nullable=True),
    sa.Column('relevant_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunityID'], ['opportunities.opportunityID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunityID')
    )
    op.create_table('user_personal_info',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('primary_role_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('highest_qualification', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('year_of_passout', sa.Integer(), nullable=False),
    sa.Column('working_status_id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_role_id'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_status_id'], ['user_status.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile_variant_projects',
    sa.Column('profile_variant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('projectDomainID', sa.UUID(), nullable=False),
    sa.Column('techstacks', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['profile_variant_id'], ['profile_variants.profile_variant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectDomainID'], ['project_domains.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_variant_id', 'project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('project_techstacks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('techstack_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['techstack_id'], ['tech_stacks.techstack_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'techstack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_techstacks')
    op.drop_table('profile_variant_projects')
    op.drop_table('user_personal_info')
    op.drop_table('sales_enablement')
    op.drop_table('projects')
    op.drop_table('profile_variants')
    op.drop_table('user_status')
    op.drop_table('user_invitations')
    op.drop_table('tech_stacks')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('project_domains')
    op.drop_table('opportunities')
    op.drop_table('job_roles')
    op.drop_table('branches')
    op.drop_table('users')
    op.drop_table('rolePermissions')
    op.drop_table('menu_roles')
    op.drop_table('roles')
    op.drop_table('platforms')
    op.drop_table('permissions')
    op.drop_table('opportunity_status')
    op.drop_table('menus')
    op.drop_table('features')
    # ### end Alembic commands ###
