"""Add comments field to technical preparation

Revision ID: 2e4c2588f219
Revises: df39bb697e6c
Create Date: 2026-08-14 11:26:16.653290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4c2588f219'
down_revision: Union[str, None] = 'df39bb697e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_opportunity_technical_preperation', sa.Column('comments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_opportunity_technical_preperation', 'comments')
    # ### end Alembic commands ###
