"""case study fields update

Revision ID: 35291a034c2b
Revises: 0c9370a82678
Create Date: 2026-08-06 00:29:52.078635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35291a034c2b'
down_revision: Union[str, None] = '0c9370a82678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('projects', 'case_study',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('projects_projectDomainID_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'project_domains', ['projectDomainID'], ['id'], ondelete='RESTRICT')
    op.drop_column('projects', 'app_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('app_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_projectDomainID_fkey', 'projects', 'project_domains', ['projectDomainID'], ['id'])
    op.alter_column('projects', 'case_study',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('projects', 'links')
    # ### end Alembic commands ###
