"""Added Assign TO  TL field 

Revision ID: 391135e09f4c
Revises: 9232aa10c0ce
Create Date: 2026-08-13 16:15:05.278633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391135e09f4c'
down_revision: Union[str, None] = '9232aa10c0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
