"""Initial schema

Revision ID: 39a3888e6494
Revises: 
Create Date: 2026-08-04 10:00:17.207316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39a3888e6494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roleName', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('menu_roles',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assignedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_id', 'role_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashedPassword', sa.String(length=150), nullable=True),
    sa.Column('refUID', sa.String(length=50), nullable=True),
    sa.Column('passwordResetAt', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('reporting_to', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporting_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('opportunities',
    sa.Column('opportunityID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('posted_date', sa.String(length=100), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('benefits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('client_information', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('ai_job_summary', sa.Text(), nullable=True),
    sa.Column('required_proposal_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('company_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunityID')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('isRevoked', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('user_personal_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('primary_role', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('highest_qualification', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('year_of_passout', sa.Integer(), nullable=False),
    sa.Column('working_status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sales_enablement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunityID', sa.Integer(), nullable=False),
    sa.Column('suggested_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sales_talking_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('outreach_template', sa.Text(), nullable=True),
    sa.Column('relevant_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunityID'], ['opportunities.opportunityID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunityID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_enablement')
    op.drop_table('user_personal_info')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('opportunities')
    op.drop_table('users')
    op.drop_table('menu_roles')
    op.drop_table('roles')
    op.drop_table('menus')
    # ### end Alembic commands ###
