"""project is_draft handlers

Revision ID: 3b5b104468bc
Revises: 8159ff8323a4
Create Date: 2026-08-07 00:27:16.789984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5b104468bc'
down_revision: Union[str, None] = '8159ff8323a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: a NOT NULL column added without one fails on
    # any existing row. It also matches Projects.is_draft, so autogenerate (which runs with
    # compare_server_default=True) does not report drift on the next revision.
    op.add_column(
        'projects',
        sa.Column('is_draft', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_draft')
    # ### end Alembic commands ###
