"""Added Opportunity Pipeline Technical Preperation 

Revision ID: 40d13560a17f
Revises: 9f0fa1effb1c
Create Date: 2026-08-11 10:36:21.986306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d13560a17f'
down_revision: Union[str, None] = '9f0fa1effb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
