"""Added firebase notification table

Revision ID: 45a54f447ed7
Revises: e3f7a1c65b04
Create Date: 2026-08-17 18:19:40.975780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a54f447ed7'
down_revision: Union[str, None] = 'e3f7a1c65b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firebase_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firebase_tokens_created_at'), 'firebase_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_firebase_tokens_fcm_token'), 'firebase_tokens', ['fcm_token'], unique=True)
    op.create_index(op.f('ix_firebase_tokens_id'), 'firebase_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_firebase_tokens_is_active'), 'firebase_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_firebase_tokens_updated_at'), 'firebase_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_firebase_tokens_user_id'), 'firebase_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firebase_tokens_user_id'), table_name='firebase_tokens')
    op.drop_index(op.f('ix_firebase_tokens_updated_at'), table_name='firebase_tokens')
    op.drop_index(op.f('ix_firebase_tokens_is_active'), table_name='firebase_tokens')
    op.drop_index(op.f('ix_firebase_tokens_id'), table_name='firebase_tokens')
    op.drop_index(op.f('ix_firebase_tokens_fcm_token'), table_name='firebase_tokens')
    op.drop_index(op.f('ix_firebase_tokens_created_at'), table_name='firebase_tokens')
    op.drop_table('firebase_tokens')
    # ### end Alembic commands ###
