"""Made URL Field in Opportunities Table Unique

Revision ID: 477d3473160e
Revises: 8fa20f300363
Create Date: 2026-08-12 12:45:50.758079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477d3473160e'
down_revision: Union[str, None] = '8fa20f300363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'apply_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'opportunities', ['apply_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='unique')
    op.alter_column('opportunities', 'apply_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
