"""Added Pipeline execution status table

Revision ID: 4ac697bae22f
Revises: 2c0fe57ddbb7
Create Date: 2026-08-10 10:08:01.925539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac697bae22f'
down_revision: Union[str, None] = '2c0fe57ddbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_execution_status',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('projects', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='pipelineexecutionstatus'), nullable=False),
    sa.Column('salesEnablement', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='pipelineexecutionstatus'), nullable=False),
    sa.Column('resourceMatch', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='pipelineexecutionstatus'), nullable=False),
    sa.Column('technicalPreperation', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='pipelineexecutionstatus'), nullable=False),
    sa.Column('execution_message', sa.String(length=255), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunityID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_execution_status')
    # ### end Alembic commands ###
