"""Added Description column to Permissions

Revision ID: 4d34d239f6aa
Revises: 36ed2facbe60
Create Date: 2026-08-04 12:03:30.383925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d34d239f6aa'
down_revision: Union[str, None] = '36ed2facbe60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('permission_key', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('description', sa.String(length=100), nullable=False))
    op.drop_constraint('permissions_permission_name_key', 'permissions', type_='unique')
    op.create_unique_constraint(None, 'permissions', ['permission_key'])
    op.drop_column('permissions', 'permission_name')
    op.add_column('rolePermissions', sa.Column('feature_id', sa.Integer(), nullable=False))
    op.drop_constraint('rolePermissions_module_id_fkey', 'rolePermissions', type_='foreignkey')
    op.create_foreign_key(None, 'rolePermissions', 'features', ['feature_id'], ['feature_id'])
    op.drop_column('rolePermissions', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolePermissions', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rolePermissions', type_='foreignkey')
    op.create_foreign_key('rolePermissions_module_id_fkey', 'rolePermissions', 'features', ['module_id'], ['feature_id'])
    op.drop_column('rolePermissions', 'feature_id')
    op.add_column('permissions', sa.Column('permission_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permissions', type_='unique')
    op.create_unique_constraint('permissions_permission_name_key', 'permissions', ['permission_name'])
    op.drop_column('permissions', 'description')
    op.drop_column('permissions', 'permission_key')
    # ### end Alembic commands ###
