"""Added project Domains

Revision ID: 523dc35bea42
Revises: ff5477aafe91
Create Date: 2026-08-05 15:19:13.896444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523dc35bea42'
down_revision: Union[str, None] = 'ff5477aafe91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign keys first
    op.drop_constraint(
        "project_domains_project_id_fkey",
        "project_domains",
        type_="foreignkey",
    )

    op.drop_constraint(
        "project_domains_domain_id_fkey",
        "project_domains",
        type_="foreignkey",
    )

    # Now it's safe to drop the obsolete table
    op.drop_table("domains")
    op.add_column('project_domains', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('project_domains', sa.Column('domain', sa.String(length=100), nullable=False))
    op.add_column('project_domains', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('project_domains', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('project_domains', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('project_domains', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.add_column('project_domains', sa.Column('createdBy', sa.UUID(), nullable=False))
    op.add_column('project_domains', sa.Column('updatedBy', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'project_domains', ['domain'])
    # op.drop_constraint('project_domains_project_id_fkey', 'project_domains', type_='foreignkey')
    # op.drop_constraint('project_domains_domain_id_fkey', 'project_domains', type_='foreignkey')
    op.create_foreign_key(None, 'project_domains', 'users', ['updatedBy'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_domains', 'users', ['createdBy'], ['user_id'], ondelete='CASCADE')
    op.drop_column('project_domains', 'project_id')
    op.drop_column('project_domains', 'created_at')
    op.drop_column('project_domains', 'domain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_domains', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_domains', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('project_domains', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_domains', type_='foreignkey')
    op.drop_constraint(None, 'project_domains', type_='foreignkey')
    op.create_foreign_key('project_domains_domain_id_fkey', 'project_domains', 'domains', ['domain_id'], ['domain_id'], ondelete='CASCADE')
    op.create_foreign_key('project_domains_project_id_fkey', 'project_domains', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_domains', type_='unique')
    op.drop_column('project_domains', 'updatedBy')
    op.drop_column('project_domains', 'createdBy')
    op.drop_column('project_domains', 'updatedAt')
    op.drop_column('project_domains', 'createdAt')
    op.drop_column('project_domains', 'is_active')
    op.drop_column('project_domains', 'description')
    op.drop_column('project_domains', 'domain')
    op.drop_column('project_domains', 'id')
    op.create_table('domains',
    sa.Column('domain_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('domain_id', name='domains_pkey'),
    sa.UniqueConstraint('domain_name', name='domains_domain_name_key')
    )
    # ### end Alembic commands ###
