"""Added Assign TO  TL field 

Revision ID: 5de82cc586ab
Revises: 391135e09f4c
Create Date: 2026-08-13 16:32:13.236786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de82cc586ab'
down_revision: Union[str, None] = '391135e09f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_opportunity_resource', sa.Column('candidate_name', sa.String(length=255), nullable=True))
    op.add_column('pipeline_opportunity_resource', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('pipeline_opportunity_resource', sa.Column('assigned_to_tl_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'pipeline_opportunity_resource', 'users', ['assigned_to_tl_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_opportunity_resource', type_='foreignkey')
    op.drop_column('pipeline_opportunity_resource', 'assigned_to_tl_by')
    op.drop_column('pipeline_opportunity_resource', 'role')
    op.drop_column('pipeline_opportunity_resource', 'candidate_name')
    # ### end Alembic commands ###
