"""Add branch table

Revision ID: 638bf2dd549d
Revises: d59780b38138
Create Date: 2026-08-07 19:51:20.701703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638bf2dd549d'
down_revision: Union[str, None] = 'd59780b38138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user_personal_info', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_personal_info', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_personal_info', 'branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_info', sa.Column('branch', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_personal_info', type_='foreignkey')
    op.drop_column('user_personal_info', 'branch_id')
    op.drop_table('branches')
    # ### end Alembic commands ###
