"""description of changes

Revision ID: 67f8e6e4931a
Revises: 8e3c9cc0d272
Create Date: 2026-08-04 14:13:29.397256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f8e6e4931a'
down_revision: Union[str, None] = '8e3c9cc0d272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolePermissions', sa.Column('isDeleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rolePermissions', 'isDeleted')
    # ### end Alembic commands ###
