"""add description to opportunity

Revision ID: 69b00bbc1c00
Revises: 6bf563435e51
Create Date: 2026-08-11 11:55:14.919001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b00bbc1c00'
down_revision: Union[str, None] = '6bf563435e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'description')
    # ### end Alembic commands ###
