"""Created Opportunity Pipeline matched resource and  Technical Preperation 

Revision ID: 6bf563435e51
Revises: 40d13560a17f
Create Date: 2026-08-11 10:40:41.900180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf563435e51'
down_revision: Union[str, None] = '40d13560a17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_opportunity_technical_preperation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('variant_title', sa.String(length=255), nullable=False),
    sa.Column('technical_briefing_note', sa.String(length=1000), nullable=False),
    sa.Column('interview_preparation_guide', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunityID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_opportunity_resource',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('variant_title', sa.String(length=255), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=False),
    sa.Column('matching_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('justification', sa.String(length=1000), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunityID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['profile_variants.profile_variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_opportunity_resource')
    op.drop_table('pipeline_opportunity_technical_preperation')
    # ### end Alembic commands ###
