"""Added Creator and Created at details for  Pipeline execution status

Revision ID: 6c4b7becc147
Revises: 4ac697bae22f
Create Date: 2026-08-10 10:20:31.244919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4b7becc147'
down_revision: Union[str, None] = '4ac697bae22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_execution_status', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('pipeline_execution_status', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.add_column('pipeline_execution_status', sa.Column('createdBy', sa.UUID(), nullable=False))
    op.add_column('pipeline_execution_status', sa.Column('updatedBy', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'pipeline_execution_status', 'users', ['createdBy'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_execution_status', 'users', ['updatedBy'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_execution_status', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_execution_status', type_='foreignkey')
    op.drop_column('pipeline_execution_status', 'updatedBy')
    op.drop_column('pipeline_execution_status', 'createdBy')
    op.drop_column('pipeline_execution_status', 'updatedAt')
    op.drop_column('pipeline_execution_status', 'createdAt')
    # ### end Alembic commands ###
