"""change client_information to jsonb

Revision ID: 73f805de9009
Revises: b6e541c71b0f
Create Date: 2026-08-05 15:03:06.607370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f805de9009'
down_revision: Union[str, None] = 'b6e541c71b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'client_information',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='client_information::jsonb',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'client_information',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               postgresql_using='client_information::text',
               existing_nullable=True)
    # ### end Alembic commands ###
