"""Added Job Roles Table

Revision ID: 786966e5269b
Revises: ec52059b38dd
Create Date: 2026-08-05 18:18:30.903587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786966e5269b'
down_revision: Union[str, None] = 'ec52059b38dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('normalizedName', sa.String(length=100), nullable=False),
    sa.Column('displayName', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('updatedBy', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('displayName'),
    sa.UniqueConstraint('normalizedName')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_roles')
    # ### end Alembic commands ###
