"""add status_id to opportunity

Revision ID: 790981364a2f
Revises: a39c00316c6f
Create Date: 2026-08-04 17:41:13.527585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790981364a2f'
down_revision: Union[str, None] = 'a39c00316c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('status_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'opportunities', 'opportunity_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'status_id')
    # ### end Alembic commands ###
