"""create profile_variants and association table

Revision ID: 7a3e4e3a2a27
Revises: 1ceadda60289
Create Date: 2026-08-06 19:31:33.005662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3e4e3a2a27'
down_revision: Union[str, None] = '1ceadda60289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_variants',
    sa.Column('profile_variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('experience', sa.String(length=255), nullable=False),
    sa.Column('highlighted_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('upload_profile', sa.String(length=255), nullable=False),
    sa.Column('certificate', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_draft', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_variant_id')
    )
    op.create_table('profile_variant_projects',
    sa.Column('profile_variant_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_variant_id'], ['profile_variants.profile_variant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_variant_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_variant_projects')
    op.drop_table('profile_variants')
    # ### end Alembic commands ###
