"""Add additional_fields to opportunities

Revision ID: 7eca583cc85d
Revises: 017f0df5a222
Create Date: 2026-07-31 18:05:35.757583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eca583cc85d'
down_revision: Union[str, None] = '017f0df5a222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('additional_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'additional_fields')
    # ### end Alembic commands ###
