"""Removed Relavent projects column in sales enablement

Revision ID: 882a6b6a4936
Revises: 7cf2062fe8e1
Create Date: 2026-08-10 18:26:15.566833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882a6b6a4936'
down_revision: Union[str, None] = '7cf2062fe8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
