"""Removed UserID column

Revision ID: 8fa20f300363
Revises: 2b4adec72046
Create Date: 2026-08-12 10:14:33.999665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa20f300363'
down_revision: Union[str, None] = '2b4adec72046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pipeline_opportunity_technical_preperation_user_id_fkey', 'pipeline_opportunity_technical_preperation', type_='foreignkey')
    op.drop_column('pipeline_opportunity_technical_preperation', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_opportunity_technical_preperation', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('pipeline_opportunity_technical_preperation_user_id_fkey', 'pipeline_opportunity_technical_preperation', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
