"""Made URL Field in Opportunities Table Unique

Revision ID: 9034d04f645b
Revises: 477d3473160e
Create Date: 2026-08-12 13:05:42.491729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9034d04f645b'
down_revision: Union[str, None] = '477d3473160e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'apply_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('opportunities', 'job_posting_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
    op.drop_constraint('opportunities_apply_url_key', 'opportunities', type_='unique')
    op.create_unique_constraint(None, 'opportunities', ['job_posting_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='unique')
    op.create_unique_constraint('opportunities_apply_url_key', 'opportunities', ['apply_url'])
    op.alter_column('opportunities', 'job_posting_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('opportunities', 'apply_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
