"""Added Opportunity Pipeline Resource match table

Revision ID: 9f0fa1effb1c
Revises: 0a145d99489a
Create Date: 2026-08-11 10:24:25.092990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0fa1effb1c'
down_revision: Union[str, None] = '0a145d99489a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
