"""Add user_id to opportunity

Revision ID: a607aed9f77c
Revises: 7eca583cc85d
Create Date: 2026-07-31 18:25:02.070197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a607aed9f77c'
down_revision: Union[str, None] = '7eca583cc85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'user_id')
    # ### end Alembic commands ###
