"""Added is Auto approved column in Resource match Table 

Revision ID: ab3a74c35a1c
Revises: 1d9e83e8658f
Create Date: 2026-08-12 18:39:53.011285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3a74c35a1c'
down_revision: Union[str, None] = '1d9e83e8658f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_opportunity_resource', sa.Column('is_auto_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_opportunity_resource', 'is_auto_approved')
    # ### end Alembic commands ###
