"""Updated Profile Variant table

Revision ID: aca7e33fc7df
Revises: f19bba9bfb2b
Create Date: 2026-08-11 16:28:50.686875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca7e33fc7df'
down_revision: Union[str, None] = 'f19bba9bfb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_opportunity_resource', sa.Column('is_selected', sa.Boolean(), nullable=True))
    op.add_column('pipeline_opportunity_resource', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('pipeline_opportunity_resource', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('pipeline_opportunity_resource', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_index('uq_one_approved_resource_per_opportunity', 'pipeline_opportunity_resource', ['opportunity_id'], unique=True, postgresql_where=sa.text('is_approved = true'))
    op.create_foreign_key(None, 'pipeline_opportunity_resource', 'users', ['approved_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_opportunity_resource', type_='foreignkey')
    op.drop_index('uq_one_approved_resource_per_opportunity', table_name='pipeline_opportunity_resource', postgresql_where=sa.text('is_approved = true'))
    op.drop_column('pipeline_opportunity_resource', 'approved_by')
    op.drop_column('pipeline_opportunity_resource', 'approved_at')
    op.drop_column('pipeline_opportunity_resource', 'is_approved')
    op.drop_column('pipeline_opportunity_resource', 'is_selected')
    # ### end Alembic commands ###
