"""add app_config table for runtime tunables

Revision ID: b3e91c07a4d2
Revises: fab585d328e4
Create Date: 2026-08-22 00:00:00.000000

Hand-written rather than autogenerated so the seed rows travel with the schema. Without
them the application still runs -- `get_config_value` falls back to APP_CONFIG_DEFAULTS --
but logs a warning on every read.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b3e91c07a4d2'
down_revision: Union[str, None] = 'fab585d328e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'app_config',
        sa.Column('id', postgresql.UUID(as_uuid=True),
                  server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('config_key', sa.String(length=100), nullable=False),
        sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('config_key', name='uq_app_config_config_key'),
    )

    # ON CONFLICT DO NOTHING so the seed is safe to re-run, and safe on a database where
    # these rows were inserted by hand before the migration was applied.
    op.execute("""
        INSERT INTO app_config (config_key, config_value, description) VALUES
          ('otp_max_attempts', '5'::jsonb,
           'Failed OTP submissions allowed before the code is rejected.'),
          ('jobkey_query_hosts', '["in.indeed.com"]'::jsonb,
           'Hosts whose query string carries the job id and must not be stripped.')
        ON CONFLICT (config_key) DO NOTHING
    """)


def downgrade() -> None:
    op.drop_table('app_config')
