"""add assigned_to to opportunity

Revision ID: b6e541c71b0f
Revises: aff6906a70c6
Create Date: 2026-08-05 12:34:56.312037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6e541c71b0f'
down_revision: Union[str, None] = 'aff6906a70c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'users', ['assigned_to'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'assigned_to')
    # ### end Alembic commands ###
