"""add system key columns to roles, user_status and opportunity_status

Revision ID: c7d4a1f9e320
Revises: b3e91c07a4d2
Create Date: 2026-08-24 00:00:00.000000

Hand-written rather than autogenerated so the name -> key backfill travels with the schema.

The columns are nullable on purpose: a key marks a row the *code* addresses. Rows an
administrator creates carry no key and need none, and PostgreSQL allows many NULLs under a
plain UNIQUE constraint, so no partial index is required.

After applying, confirm nothing was missed -- any row already renamed in this environment
will not have matched the backfill:

    SELECT unnest(ARRAY['super_admin','user','bd_executive','manager','team_lead']) AS missing
    EXCEPT SELECT role_key FROM roles WHERE role_key IS NOT NULL;

    SELECT unnest(ARRAY['on_bench']) AS missing
    EXCEPT SELECT status_key FROM user_status WHERE status_key IS NOT NULL;

    SELECT unnest(ARRAY['new','selected','rejected','not_qualified']) AS missing
    EXCEPT SELECT status_key FROM opportunity_status WHERE status_key IS NOT NULL;

Each must return zero rows. Anything listed needs its key set by hand.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d4a1f9e320'
down_revision: Union[str, None] = 'b3e91c07a4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('roles', sa.Column('role_key', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_roles_role_key', 'roles', ['role_key'])

    op.add_column('user_status', sa.Column('status_key', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_user_status_status_key', 'user_status', ['status_key'])

    op.add_column('opportunity_status', sa.Column('status_key', sa.String(length=50), nullable=True))
    op.create_unique_constraint(
        'uq_opportunity_status_status_key', 'opportunity_status', ['status_key']
    )

    # Backfill from the display names the code matched on until now. Case-insensitive and
    # whitespace-tolerant because these are administrator-entered rows, not schema values.
    op.execute("""
        UPDATE roles SET role_key = v.key FROM (VALUES
            ('Super Admin',  'super_admin'),
            ('User',         'user'),
            ('BD-Executive', 'bd_executive'),
            ('Manager',      'manager'),
            ('Team Lead',    'team_lead')
        ) AS v(name, key)
        WHERE btrim(lower(roles."roleName")) = lower(v.name)
          AND roles.role_key IS NULL
    """)

    op.execute("""
        UPDATE user_status SET status_key = 'on_bench'
        WHERE btrim(lower("displayName")) = 'on bench' AND status_key IS NULL
    """)

    op.execute("""
        UPDATE opportunity_status SET status_key = v.key FROM (VALUES
            ('New',           'new'),
            ('Selected',      'selected'),
            ('Rejected',      'rejected'),
            ('Not Qualified', 'not_qualified')
        ) AS v(name, key)
        WHERE btrim(lower(opportunity_status.status)) = lower(v.name)
          AND opportunity_status.status_key IS NULL
    """)


def downgrade() -> None:
    op.drop_constraint('uq_opportunity_status_status_key', 'opportunity_status', type_='unique')
    op.drop_column('opportunity_status', 'status_key')

    op.drop_constraint('uq_user_status_status_key', 'user_status', type_='unique')
    op.drop_column('user_status', 'status_key')

    op.drop_constraint('uq_roles_role_key', 'roles', type_='unique')
    op.drop_column('roles', 'role_key')
