"""add is_active to specializations

Revision ID: c98aa7191698
Revises: 30f6feca252a
Create Date: 2026-08-26 19:46:22.052680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98aa7191698'
down_revision: Union[str, None] = '30f6feca252a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('specializations', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specializations', 'is_active')
    op.drop_column('education', 'is_active')
    # ### end Alembic commands ###
