"""message

Revision ID: d230537fb7b8
Revises: 62a7746a97cb
Create Date: 2026-07-31 14:15:36.866073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd230537fb7b8'
down_revision: Union[str, None] = '62a7746a97cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('opportunityID', sa.UUID(), nullable=False))
    op.drop_column('opportunities', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('opportunities', 'opportunityID')
    # ### end Alembic commands ###
