"""add_platform_fields

Revision ID: d59780b38138
Revises: f03542389375
Create Date: 2026-08-07 17:56:56.921275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59780b38138'
down_revision: Union[str, None] = 'f03542389375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('is_account_linked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('platforms', sa.Column('account_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'account_url')
    op.drop_column('platforms', 'is_account_linked')
    # ### end Alembic commands ###
