"""Refactor UserPersonalInfo and fullName

Revision ID: d76248adc166
Revises: 5f579d326e3e
Create Date: 2026-08-06 12:47:39.032849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76248adc166'
down_revision: Union[str, None] = '5f579d326e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_info', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user_personal_info', sa.Column('last_name', sa.String(length=100), nullable=True))
    
    op.execute("""
        UPDATE user_personal_info
        SET first_name = users."fullName",
            last_name = NULL
        FROM users
        WHERE users.user_id = user_personal_info.user_id
    """)
    
    op.alter_column('user_personal_info', 'first_name', nullable=False)
    op.add_column('user_personal_info', sa.Column('primary_role_id', sa.Integer(), nullable=True))
    op.add_column('user_personal_info', sa.Column('working_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_upi_primary_role_id', 'user_personal_info', 'job_roles', ['primary_role_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_upi_working_status_id', 'user_personal_info', 'user_status', ['working_status_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_personal_info', 'primary_role')
    op.drop_column('user_personal_info', 'working_status')
    op.drop_column('users', 'fullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user_personal_info', sa.Column('working_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user_personal_info', sa.Column('primary_role', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_upi_working_status_id', 'user_personal_info', type_='foreignkey')
    op.drop_constraint('fk_upi_primary_role_id', 'user_personal_info', type_='foreignkey')
    op.drop_column('user_personal_info', 'working_status_id')
    op.drop_column('user_personal_info', 'primary_role_id')
    op.drop_column('user_personal_info', 'last_name')
    op.drop_column('user_personal_info', 'first_name')
    # ### end Alembic commands ###
