"""empty message

Revision ID: d83431234950
Revises: 45a54f447ed7
Create Date: 2026-08-18 14:10:47.306322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd83431234950'
down_revision: Union[str, None] = '45a54f447ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_SIGNUP', 'PASSWORD_RESET', 'OPPORTUNITY_CREATED', 'OPPORTUNITY_UPDATED', 'OPPORTUNITY_STATUS_CHANGED', 'OPPORTUNITY_DELETED', 'OPPORTUNITY_AI_INGESTED', 'PIPELINE_PROJECT_CREATED', 'PIPELINE_PROJECT_UPDATED', 'PIPELINE_PROJECT_DELETED', 'PIPELINE_RESOURCE_CREATED', 'PIPELINE_RESOURCE_UPDATED', 'PIPELINE_RESOURCE_DELETED', 'PIPELINE_RESOURCE_SELECTED', 'PIPELINE_RESOURCE_ASSIGNED_TO_TL', 'PIPELINE_RESOURCE_APPROVED', 'PIPELINE_RESOURCE_AUTO_APPROVED', 'PIPELINE_RESOURCE_REJECTED', 'PIPELINE_TECH_PREP_CREATED', 'PIPELINE_TECH_PREP_UPDATED', 'PIPELINE_TECH_PREP_DELETED', 'PIPELINE_TECH_PREP_COMMENTED', 'PROFILE_VARIANT_CREATED', 'PROFILE_VARIANT_UPDATED', 'PROFILE_VARIANT_DELETED', 'PROFILE_DOWNLOADED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'CASE_STUDY_DOWNLOADED', 'SALES_ENABLEMENT_CREATED', 'SALES_ENABLEMENT_UPDATED', 'SALES_ENABLEMENT_DELETED', 'USER_INVITED', 'USER_ROLE_CHANGED', 'USER_STATUS_CHANGED', 'ROLE_PERMISSION_CREATED', 'ROLE_PERMISSION_UPDATED', 'ROLE_PERMISSION_DELETED', 'CSV_EXPORTED', name='log_action'), nullable=False),
    sa.Column('module', sa.Enum('AUTH', 'OPPORTUNITY', 'PIPELINE', 'PROFILE_VARIANT', 'PROJECT', 'SALES_ENABLEMENT', 'USER_MANAGEMENT', 'SETTINGS', 'EXPORT', name='log_module'), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_logs_entity_id'), 'system_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index(op.f('ix_system_logs_performed_at'), 'system_logs', ['performed_at'], unique=False)
    op.create_index('ix_system_logs_performed_at_module', 'system_logs', [sa.text('performed_at DESC'), 'module'], unique=False)
    op.create_index(op.f('ix_system_logs_performed_by'), 'system_logs', ['performed_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_performed_by'), table_name='system_logs')
    op.drop_index('ix_system_logs_performed_at_module', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_performed_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_entity_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
