"""Update opportunity status and user fields

Revision ID: e243f10664fb
Revises: a607aed9f77c
Create Date: 2026-08-03 12:23:39.817021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e243f10664fb'
down_revision: Union[str, None] = 'a607aed9f77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_enablement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunityID', sa.UUID(), nullable=False),
    sa.Column('suggested_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sales_talking_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('outreach_template', sa.Text(), nullable=True),
    sa.Column('relevant_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunityID'], ['opportunities.opportunityID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunityID')
    )
    op.add_column('opportunities', sa.Column('createdBy', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('updatedBy', sa.UUID(), nullable=True))
    
    op.execute('DELETE FROM opportunities WHERE user_id IS NULL')
    op.execute('UPDATE opportunities SET "createdBy" = user_id, "updatedBy" = user_id')
    
    op.alter_column('opportunities', 'createdBy', nullable=False)
    op.alter_column('opportunities', 'updatedBy', nullable=False)
    op.drop_constraint('opportunities_user_id_fkey', 'opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'opportunities', 'users', ['createdBy'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'opportunities', 'users', ['updatedBy'], ['user_id'], ondelete='CASCADE')
    op.drop_column('opportunities', 'user_id')
    op.drop_column('opportunities', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_foreign_key('opportunities_user_id_fkey', 'opportunities', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('opportunities', 'updatedBy')
    op.drop_column('opportunities', 'createdBy')
    op.drop_table('sales_enablement')
    # ### end Alembic commands ###
