"""Add createdBy and updatedBy to sales_enablement

Revision ID: e7184806c225
Revises: e243f10664fb
Create Date: 2026-08-03 14:53:44.329072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7184806c225'
down_revision: Union[str, None] = 'e243f10664fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_enablement', sa.Column('createdBy', sa.UUID(), nullable=False))
    op.add_column('sales_enablement', sa.Column('updatedBy', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sales_enablement', 'users', ['createdBy'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales_enablement', 'users', ['updatedBy'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_enablement', type_='foreignkey')
    op.drop_constraint(None, 'sales_enablement', type_='foreignkey')
    op.drop_column('sales_enablement', 'updatedBy')
    op.drop_column('sales_enablement', 'createdBy')
    # ### end Alembic commands ###
