"""add user_id to profile_variants

Revision ID: e7d1f0f4cd89
Revises: 7a3e4e3a2a27
Create Date: 2026-08-06 21:40:29.612565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d1f0f4cd89'
down_revision: Union[str, None] = '7a3e4e3a2a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_variants', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'profile_variants', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_variants', type_='foreignkey')
    op.drop_column('profile_variants', 'user_id')
    # ### end Alembic commands ###
