"""link profile_variants role to job_roles and add fields to association table

Revision ID: f03542389375
Revises: 3b5b104468bc
Create Date: 2026-08-07 15:45:49.438869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f03542389375'
down_revision: Union[str, None] = '3b5b104468bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_variant_projects', sa.Column('project_name', sa.String(length=255), nullable=False))
    op.add_column('profile_variant_projects', sa.Column('projectDomainID', sa.Integer(), nullable=False))
    op.add_column('profile_variant_projects', sa.Column('techstacks', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('profile_variant_projects', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('profile_variant_projects', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_unique_constraint(None, 'profile_variant_projects', ['project_name'])
    op.create_foreign_key(None, 'profile_variant_projects', 'project_domains', ['projectDomainID'], ['id'], ondelete='RESTRICT')
    op.alter_column('profile_variants', 'role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="role::integer")
    op.create_foreign_key(None, 'profile_variants', 'job_roles', ['role'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_variants', type_='foreignkey')
    op.alter_column('profile_variants', 'role',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'profile_variant_projects', type_='foreignkey')
    op.drop_constraint(None, 'profile_variant_projects', type_='unique')
    op.drop_column('profile_variant_projects', 'links')
    op.drop_column('profile_variant_projects', 'description')
    op.drop_column('profile_variant_projects', 'techstacks')
    op.drop_column('profile_variant_projects', 'projectDomainID')
    op.drop_column('profile_variant_projects', 'project_name')
    # ### end Alembic commands ###
