"""Drop specialization from user

Revision ID: f19bba9bfb2b
Revises: 34758f00ba5f
Create Date: 2026-08-11 15:34:09.938922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19bba9bfb2b'
down_revision: Union[str, None] = '34758f00ba5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialization', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
