"""Added Feature Description column

Revision ID: f73da3778b13
Revises: 4d34d239f6aa
Create Date: 2026-08-04 12:13:13.648704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73da3778b13'
down_revision: Union[str, None] = '4d34d239f6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'description')
    # ### end Alembic commands ###
