"""Updated Opportunity resource table to add approve Authority

Revision ID: fab585d328e4
Revises: c8d5e2a17f43
Create Date: 2026-08-21 21:17:45.093519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab585d328e4'
down_revision: Union[str, None] = 'c8d5e2a17f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_opportunity_resource', sa.Column('approval_authority_id', sa.UUID(), nullable=True))
    op.drop_index('uq_one_approved_resource_per_opportunity', table_name='pipeline_opportunity_resource', postgresql_where="(status = 'APPROVED'::approvalstatus)")
    op.create_foreign_key(None, 'pipeline_opportunity_resource', 'users', ['approval_authority_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_opportunity_resource', type_='foreignkey')
    op.create_index('uq_one_approved_resource_per_opportunity', 'pipeline_opportunity_resource', ['opportunity_id'], unique=True, postgresql_where="(status = 'APPROVED'::approvalstatus)")
    op.drop_column('pipeline_opportunity_resource', 'approval_authority_id')
    # ### end Alembic commands ###
