"""add new fields in opportunity

Revision ID: fe761be02bab
Revises: 8e3c9cc0d272
Create Date: 2026-08-04 14:49:46.307387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe761be02bab'
down_revision: Union[str, None] = '8e3c9cc0d272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('job_posting_url', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('company_website', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('additional_notes', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('is_ai_scraped', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('rolePermissions', 'isDeleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolePermissions', sa.Column('isDeleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('opportunities', 'is_ai_scraped')
    op.drop_column('opportunities', 'additional_notes')
    op.drop_column('opportunities', 'company_website')
    op.drop_column('opportunities', 'job_posting_url')
    # ### end Alembic commands ###
