"""Standardised the database

Revision ID: ff5477aafe91
Revises: 73f805de9009
Create Date: 2026-08-05 15:15:37.213566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5477aafe91'
down_revision: Union[str, None] = '73f805de9009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('case_study', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('app_link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'app_link')
    op.drop_column('projects', 'case_study')
    # ### end Alembic commands ###
