class ErrorCode:

    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    NOT_ALLOWED = "NOT_ALLOWED"
    INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN"
    INVALID_OTP = "INVALID_OTP"
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
    CONFIRM_PASSWORD_MISMATCH = "CONFIRM_PASSWORD_MISMATCH"
    
    # Project
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_ALREADY_EXISTS = "PROJECT_ALREADY_EXISTS"
    DOMAIN_NOT_FOUND = "DOMAIN_NOT_FOUND"
    TECHSTACK_NOT_FOUND = "TECHSTACK_NOT_FOUND"

    # Opportunity
    OPPORTUNITY_ALREADY_EXISTS = "OPPORTUNITY_ALREADY_EXISTS"
    OPPORTUNITY_NOT_FOUND = "OPPORTUNITY_NOT_FOUND"
    INVALID_OPPORTUNITY_ID = "INVALID_OPPORTUNITY_ID"

    # Case study upload
    CASE_STUDY_NOT_FOUND = "CASE_STUDY_NOT_FOUND"
    CASE_STUDY_INVALID = "CASE_STUDY_INVALID"
    CASE_STUDY_UNSUPPORTED_TYPE = "CASE_STUDY_UNSUPPORTED_TYPE"
    CASE_STUDY_TOO_LARGE = "CASE_STUDY_TOO_LARGE"

    # Invitation 
    INVITATION_CANCELLED = "INVITATION_CANCELLED"
    INVITATION_USED = "INVITATION_USED"

    # Notifications
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    NOTIFICATION_TYPE_NOT_CONFIGURED = "NOTIFICATION_TYPE_NOT_CONFIGURED"

    # Settings / role permissions
    FEATURE_NOT_FOUND = "FEATURE_NOT_FOUND"
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND"
    CONFLICTING_PERMISSION_TOGGLE = "CONFLICTING_PERMISSION_TOGGLE"
    LEGACY_ROLE_DELETE_NOT_ALLOWED = "LEGACY_ROLE_DELETE_NOT_ALLOWED"
    LEGACY_ROLE_UPDATE_NOT_ALLOWED = "LEGACY_ROLE_UPDATE_NOT_ALLOWED"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    ROLE_REASSIGNMENT_FAILED = "ROLE_REASSIGNMENT_FAILED"

    # Database
    DATABASE_ERROR = "DATABASE_ERROR"
    DUPLICATE_RECORD = "DUPLICATE_RECORD"
    FOREIGN_KEY_ERROR = "FOREIGN_KEY_ERROR"
    DATA_NOT_FOUND = "DATA_NOT_FOUND"

    # AI Service
    AI_SERVICE_ERROR = "AI_SERVICE_ERROR"
    AI_CONNECT_ERROR = "AI_CONNECT_ERROR"
    AI_CONNECT_TIMEOUT = "AI_CONNECT_TIMEOUT"
    AI_READ_TIMEOUT = "AI_READ_TIMEOUT"
    AI_WRITE_TIMEOUT = "AI_WRITE_TIMEOUT"
    AI_POOL_TIMEOUT = "AI_POOL_TIMEOUT"
    AI_TIMEOUT_ERROR = "AI_TIMEOUT_ERROR"
    AI_HTTP_STATUS_ERROR = "AI_HTTP_STATUS_ERROR"
    # the AI answered, but the failure was its own rather than anything about the request
    AI_UPSTREAM_FAILURE = "AI_UPSTREAM_FAILURE"
    AI_REQUEST_ERROR = "AI_REQUEST_ERROR"
    AI_NETWORK_ERROR = "AI_NETWORK_ERROR"
    AI_REMOTE_PROTOCOL_ERROR = "AI_REMOTE_PROTOCOL_ERROR"
    AI_TOO_MANY_REDIRECTS = "AI_TOO_MANY_REDIRECTS"
    AI_INVALID_RESPONSE_FORMAT = "AI_INVALID_RESPONSE_FORMAT"

    # Domains
    CANT_FETCH_PROJECT_FILTERS = "CANT_FETCH_PROJECT_FILTERS"

    # AWS S3
    S3_FILE_NOT_FOUND  = "S3_FILE_NOT_FOUND"
    S3_UPLOAD_FAILED = "S3_UPLOAD_FAILED"
    S3_DOWNLOAD_FAILED = "S3_DOWNLOAD_FAILED"
    S3_STREAM_FAILED = "S3_STREAM_FAILED"
    S3_DELETE_FAILED = "S3_DELETE_FAILED"
    S3_FILE_EXISTS_CHECK_FAILED = "S3_FILE_EXISTS_CHECK_FAILED"
    S3_CONNECTION_FAILED = "S3_CONNECTION_FAILED"
    S3_CLIENT_NOT_INITIALIZED = "S3_CLIENT_NOT_INITIALIZED"
    S3_INVALID_OBJECT_KEY = "S3_INVALID_OBJECT_KEY"
    S3_PRESIGNED_URL_FAILED = "S3_PRESIGNED_URL_FAILED"