class ErrorCode:

    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    SESSION_EXPIRED = "SESSION_EXPIRED"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    # Database
    DATABASE_ERROR = "DATABASE_ERROR"
    DUPLICATE_RECORD = "DUPLICATE_RECORD"
    FOREIGN_KEY_ERROR = "FOREIGN_KEY_ERROR"

    # AI Service
    AI_SERVICE_ERROR = "AI_SERVICE_ERROR"
    AI_CONNECT_ERROR = "AI_CONNECT_ERROR"
    AI_CONNECT_TIMEOUT = "AI_CONNECT_TIMEOUT"
    AI_READ_TIMEOUT = "AI_READ_TIMEOUT"
    AI_WRITE_TIMEOUT = "AI_WRITE_TIMEOUT"
    AI_POOL_TIMEOUT = "AI_POOL_TIMEOUT"
    AI_TIMEOUT_ERROR = "AI_TIMEOUT_ERROR"
    AI_HTTP_STATUS_ERROR = "AI_HTTP_STATUS_ERROR"
    AI_REQUEST_ERROR = "AI_REQUEST_ERROR"
    AI_NETWORK_ERROR = "AI_NETWORK_ERROR"
    AI_REMOTE_PROTOCOL_ERROR = "AI_REMOTE_PROTOCOL_ERROR"
    AI_TOO_MANY_REDIRECTS = "AI_TOO_MANY_REDIRECTS"
    AI_INVALID_RESPONSE_FORMAT = "AI_INVALID_RESPONSE_FORMAT"

